#!/usr/bin/env python3
"""Generate the runtime-component Go package-source table from the canonical JSON SSOT."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

POLICY_SCHEMA = "prototype-ordax.runtime-component-package-policy/1"
CANONICAL_APPS_REPOSITORY = "ordaxsystems/ordax-apps"
APP_ID_RE = re.compile(r"^[a-z][a-z0-9-]{0,63}$")

class GenerationError(RuntimeError):
    pass

def load_sources(path: Path) -> dict[str, str]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise GenerationError(f"cannot read canonical runtime package policy: {path}") from exc
    if not isinstance(value, dict) or value.get("$schema") != POLICY_SCHEMA:
        raise GenerationError("runtime package policy schema is invalid")
    sources = value.get("canonical_package_source_repository_by_component")
    if not isinstance(sources, dict) or not sources:
        raise GenerationError("canonical package source mapping is missing")
    normalized: dict[str, str] = {}
    for component_id, repository in sorted(sources.items()):
        if not isinstance(component_id, str) or APP_ID_RE.fullmatch(component_id) is None:
            raise GenerationError(f"invalid component id in package source policy: {component_id!r}")
        if repository != CANONICAL_APPS_REPOSITORY:
            raise GenerationError(f"unexpected package source repository for {component_id}")
        normalized[component_id] = repository
    return normalized

def render(sources: dict[str, str]) -> str:
    lines = [
        "// Code generated by tools/app-policy/render_runtime_package_source_policy.py; DO NOT EDIT.",
        "// Source of truth: docs/contracts/runtime-component-package.json",
        "",
        "package main",
        "",
        "var canonicalExternalComponentSourceRepositories = map[string]string{",
    ]
    for component_id in sources:
        lines.append(f'\t"{component_id}": appsSourceRepository,')
    lines.extend(["}", ""])
    return "\n".join(lines)

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--policy", type=Path, default=Path("docs/contracts/runtime-component-package.json"))
    parser.add_argument("--out", type=Path, default=Path("tools/runtime-component-channel/external_sources_generated.go"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        expected = render(load_sources(args.policy))
        if args.check:
            try:
                current = args.out.read_text(encoding="utf-8")
            except (OSError, UnicodeError) as exc:
                raise GenerationError(f"generated Go source is unavailable: {args.out}") from exc
            if current != expected:
                raise GenerationError("generated Go package source policy drifted from canonical JSON SSOT")
            print("ORDAX_RUNTIME_PACKAGE_SOURCE_SSOT=PASS")
            return 0
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(expected, encoding="utf-8", newline="\n")
        print(f"wrote {args.out}")
        return 0
    except GenerationError as exc:
        print(f"ORDAX_RUNTIME_PACKAGE_SOURCE_SSOT=FAIL\n{exc}", file=sys.stderr)
        return 1

if __name__ == "__main__":
    raise SystemExit(main())
