import { useState } from 'react';
import { Crown, Cpu, HardDrive, Zap, CreditCard, FileText, ShieldCheck, MonitorSmartphone, Fingerprint, Download, Trash2, Info, UserRound, LockKeyhole, Mail, Search, ChevronDown, ChevronRight, CircleHelp, Camera, Globe, Bell, History, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { sections, type AccountPath, unavailableMessage } from '@/lib/account/model';
import { useOfficialAccountSession } from '@/lib/account/official-session';
import { ConsumptionChart } from './overview';
import { IntegrationPanel } from './integration-panel';
import mark from '@/assets/ordax-mark.png';
import landscape from '@/assets/ordax-landscape.jpg';
function Empty({icon:Icon=FileText,title,description}:{icon?:typeof FileText,title:string,description:string}) { return <div className="empty-state"><span className="empty-icon"><Icon/></span><h3>{title}</h3><p>{description}</p><span className="unavailable-chip"><span/>Serviços não conectados</span></div> }
function Field({label,placeholder,type='text'}:{label:string,placeholder:string,type?:string}) {return <label className="form-field"><span>{label}</span><input type={type} placeholder={placeholder} disabled/><small>Disponível após conectar a conta</small></label>}
const faqs=[{q:'Onde encontro meu plano e minha assinatura?',a:'A seção Plano e assinatura reúne o plano contratado, os benefícios e as opções de alteração. Essas informações dependem da conexão com o serviço de assinatura OrdaX.'},{q:'Como acompanho meu consumo de IA?',a:'Na seção Consumo e limites, você pode filtrar o período e consultar inteligência artificial, armazenamento e APIs. Sem uma conexão com os serviços, nenhum valor é estimado ou inventado.'},{q:'Como acesso minhas faturas?',a:'Pagamentos e faturas reúne documentos fiscais e cobranças. Faturas e recibos poderão ser baixados quando o serviço de faturamento estiver integrado.'},{q:'Como protejo minha conta?',a:'Em Segurança e acesso você encontra os controles de senha e verificação em duas etapas. Meus dispositivos permite consultar sessões autorizadas quando os serviços de identidade estiverem disponíveis.'},{q:'Posso exportar ou excluir meus dados?',a:'Os controles ficam em Dados e privacidade. Para sua proteção, a exportação e a exclusão exigem uma conta autenticada e o serviço de privacidade conectado.'}];
export function AccountDetails({path}:{path:AccountPath}) {
 const official = useOfficialAccountSession();
 const section=sections.find(s=>s.path===path)??sections[0];
 const [period,setPeriod]=useState('Este mês'); const [tab,setTab]=useState('Visão geral'); const [faq,setFaq]=useState<number|null>(0); const [search,setSearch]=useState(''); const [notice,setNotice]=useState(false); const [prefs,setPrefs]=useState({security:true,usage:true,news:false}); const [locale,setLocale]=useState('pt-BR');
 return <><header className="detail-page-heading"><span className="detail-heading-icon"><section.icon/></span><div><div className="eyebrow">CENTRAL DA CONTA</div><h1>{section.title}</h1><p>{section.description}</p></div></header>
 {path!=='/suporte'&&path!=='/preferencias'&&<div className="inline-notice"><Info/><span>{unavailableMessage}</span></div>}
 <IntegrationPanel path={path}/>
 {path==='/dados-pessoais'&&<section className="settings-section"><div className="settings-title"><h2>Seu perfil</h2><p>Uma identidade em todo o ecossistema OrdaX.</p></div><div className="profile-edit"><span className="large-avatar"><UserRound/></span><div><h3>Foto de perfil</h3><p>Sua imagem no OrdaX Web e OS.</p><Button variant="outline" size="sm" disabled><Camera/>Alterar foto</Button></div></div><div className="form-grid"><Field label="Nome completo" placeholder="Seu nome"/><Field label="Nome de exibição" placeholder="Como você gostaria de ser chamado"/>{official.status==='authenticated'&&official.email?<label className="form-field"><span>E-mail</span><input type="email" value={official.email} disabled readOnly/><small>Informação da sessão autenticada</small></label>:<Field label="E-mail" type="email" placeholder="Seu e-mail"/>}<Field label="Telefone" type="tel" placeholder="Seu telefone"/><Field label="País ou região" placeholder="Não disponível"/><Field label="Documento fiscal" placeholder="Não disponível"/></div><div className="form-actions"><span><LockKeyhole/>Seus dados pessoais permanecem protegidos.</span><Button disabled>Salvar alterações</Button></div></section>}
 {path==='/assinatura'&&<><section className="subscription-banner"><img className="subscription-landscape" src={landscape} width="1920" height="640" alt="Universo OrdaX"/><div><span className="eyebrow"><Crown/> SUA ASSINATURA ORDAX</span><h2>Seu universo de possibilidades.</h2><p>Informações de plano, benefícios e renovação<br/>estarão reunidas aqui.</p><span className="profile-label">Plano não disponível</span></div><img className="subscription-mark" src={mark} width="180" height="180" alt="Símbolo OrdaX"/></section><section className="settings-section"><div className="settings-title"><h2>Detalhes da assinatura</h2><p>Sem plano ou cobrança presumidos.</p></div><div className="detail-facts">{['Plano contratado','Ciclo de cobrança','Próxima renovação','Valor da assinatura'].map(t=><div key={t}><span>{t}</span><strong>Não disponível</strong></div>)}</div><div className="form-actions"><Button variant="outline" disabled>Alterar plano</Button><Button variant="ghost" disabled>Cancelar assinatura</Button></div></section><section className="settings-section"><h2>Planos e benefícios</h2><Empty icon={Crown} title="Catálogo de planos não conectado" description="A comparação de planos, preços e limites será exibida a partir do catálogo oficial OrdaX."/></section></>}
 {path==='/consumo'&&<><div className="consumption-toolbar"><div className="segment-tabs">{['Visão geral','IA','Armazenamento','APIs'].map(t=><Button variant="ghost" key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</Button>)}</div><label className="period-select"><span className="sr-only">Período de consumo</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option>Este mês</option><option>Últimos 7 dias</option><option>Últimos 30 dias</option><option>Este ano</option></select><ChevronDown/></label></div><div className="consumption-stats">{[{name:'Créditos de IA',icon:Cpu},{name:'Armazenamento',icon:HardDrive},{name:'APIs e serviços',icon:Zap}].filter(s=>tab==='Visão geral'||(tab==='IA'&&s.name==='Créditos de IA')||(tab==='Armazenamento'&&s.name===tab)||(tab==='APIs'&&s.name==='APIs e serviços')).map(s=><article key={s.name} className="account-card stat-card"><s.icon/><span>{s.name}</span><strong>—</strong><small>Uso e limite indisponíveis</small><div className="resource-track"/></article>)}</div><section className="account-card chart-card"><div className="chart-heading"><div><h2>Utilização · {tab}</h2><p>{period} · Sem dados conectados</p></div><Button variant="outline" size="sm" disabled><Download/>Exportar</Button></div><ConsumptionChart period={period}/></section><div className="inline-notice"><Info/>Os filtros alteram o período de consulta. Nenhuma métrica é estimada sem dados oficiais.</div></>}
 {path==='/faturamento'&&<><div className="billing-overview"><section className="account-card"><h2>Próxima cobrança</h2><h3 className="billing-large">—</h3><p className="text-muted-foreground text-sm">Valor e data não disponíveis</p></section><section className="account-card"><div className="flex items-center justify-between"><h2>Método de pagamento</h2><CreditCard className="cyan"/></div><p className="my-5 text-muted-foreground text-sm">Nenhum método disponível para consulta.</p><Button variant="outline" disabled>Adicionar método</Button></section></div><section className="settings-section"><div className="settings-title"><h2>Histórico de faturamento</h2><Button variant="outline" size="sm" disabled><Download/>Baixar faturas</Button></div><div className="table-header"><span>Documento</span><span>Data</span><span>Valor</span><span>Status</span></div><Empty title="Nenhuma fatura disponível" description="Faturas, recibos e histórico de cobranças aparecerão após a conexão com o faturamento."/></section><section className="settings-section"><h2>Dados fiscais</h2><div className="form-grid mt-6"><Field label="Nome ou razão social" placeholder="Não disponível"/><Field label="CPF ou CNPJ" placeholder="Não disponível"/><Field label="Endereço de faturamento" placeholder="Não disponível"/><Field label="E-mail de faturamento" placeholder="Não disponível"/></div><Button className="mt-5" disabled>Salvar dados fiscais</Button></section></>}
 {path==='/seguranca'&&<><section className="settings-section"><div className="setting-row"><span className="management-icon"><LockKeyhole/></span><div><h2>Senha de acesso</h2><p>Altere a senha que protege sua conta.</p></div><Button variant="outline" disabled>Alterar senha</Button></div><div className="setting-row"><span className="management-icon"><ShieldCheck/></span><div><h2>Verificação em duas etapas</h2><p>Uma camada extra de proteção para sua identidade.</p><small>Status não disponível</small></div><Button variant="outline" disabled>Configurar</Button></div><div className="setting-row"><span className="management-icon"><Mail/></span><div><h2>Recuperação da conta</h2><p>Gerencie o e-mail de recuperação da sua conta.</p></div><Button variant="outline" disabled>Gerenciar</Button></div></section><section className="settings-section"><h2>Histórico de acesso</h2><Empty icon={History} title="Histórico de segurança não disponível" description="Os eventos de acesso serão consultados pelo serviço de identidade OrdaX."/></section></>}
 {path==='/dispositivos'&&<section className="settings-section"><div className="settings-title"><div><h2>Dispositivos autorizados</h2><p>OrdaX OS, Web e dispositivos móveis.</p></div><Button variant="outline" disabled>Encerrar outras sessões</Button></div><Empty icon={MonitorSmartphone} title="Nenhuma sessão disponível para consulta" description="Não é possível identificar dispositivos conectados antes da integração com os serviços de autenticação."/></section>}
 {path==='/privacidade'&&<><section className="settings-section"><h2>Privacidade e consentimentos</h2>{[{title:'Dados essenciais',text:'Dados necessários para o funcionamento e a segurança da conta.'},{title:'Análise de uso',text:'Consentimento para informações que ajudam a melhorar o OrdaX.'},{title:'Comunicações personalizadas',text:'Preferências de comunicação vinculadas à sua identidade.'}].map(s=><div className="setting-row" key={s.title}><Fingerprint/><div><h3>{s.title}</h3><p>{s.text}</p></div><span className="text-muted-foreground text-xs">Não disponível</span></div>)}</section><section className="settings-section"><div className="setting-row"><Download className="cyan"/><div><h2>Exportar meus dados</h2><p>Uma cópia das suas informações pessoais e do histórico da conta.</p></div><Button variant="outline" disabled>Solicitar exportação</Button></div></section><section className="settings-section danger-section"><div className="setting-row"><Trash2/><div><h2>Excluir conta</h2><p>A exclusão permanente requer autenticação e confirmação da sua identidade.</p></div><Button variant="destructive" disabled>Excluir minha conta</Button></div></section></>}
 {path==='/preferencias'&&<><div className="inline-notice"><Info/>Prévia de preferências nesta sessão. Alterações não são salvas na conta.</div><section className="settings-section"><div className="setting-row"><Globe className="cyan"/><div><h2>Idioma e região</h2><p>Idioma preferido para sua conta, quando o serviço estiver conectado.</p></div><select aria-label="Idioma preferido" value={locale} onChange={e=>setLocale(e.target.value)}><option value="pt-BR">Português (Brasil)</option><option value="en">English</option><option value="es">Español</option></select></div><div className="setting-row"><MonitorSmartphone className="cyan"/><div><h2>Aparência</h2><p>Identidade visual OrdaX.</p></div><span className="profile-label">Escuro</span></div></section><section className="settings-section"><h2>Notificações e comunicações</h2>{[{key:'security' as const,title:'Segurança da conta',text:'Alertas de acesso e alterações importantes.'},{key:'usage' as const,title:'Consumo e assinatura',text:'Atualizações de recursos, limites e faturamento.'},{key:'news' as const,title:'Novidades OrdaX',text:'Lançamentos e novidades do ecossistema.'}].map(s=><div className="setting-row" key={s.key}><Bell/><div><h3>{s.title}</h3><p>{s.text}</p></div><Switch aria-label={s.title} checked={prefs[s.key]} onCheckedChange={v=>setPrefs({...prefs,[s.key]:v})}/></div>)}<div className="form-actions"><span className="text-muted-foreground text-xs">Prévia local · não persistida</span><Button variant="outline" onClick={()=>setPrefs({security:true,usage:true,news:false})}><RefreshCw/>Restaurar prévia</Button></div></section></>}
 {path==='/atividade'&&<section className="settings-section"><div className="settings-title"><h2>Histórico da conta</h2><label className="period-select"><select aria-label="Período de atividade" value={period} onChange={e=>setPeriod(e.target.value)}><option>Este mês</option><option>Últimos 7 dias</option><option>Últimos 30 dias</option></select><ChevronDown/></label></div><Empty icon={History} title="Nenhuma atividade disponível" description={`Acessos e alterações de ${period.toLowerCase()} serão exibidos quando o serviço de atividade estiver conectado.`}/></section>}
 {path==='/suporte'&&<><section className="help-search"><CircleHelp/><h2>Como podemos ajudar?</h2><label className="search-field"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Busque por assinatura, segurança, faturas..." aria-label="Buscar ajuda"/></label></section><section className="settings-section"><h2>Perguntas frequentes</h2><div className="faq-list">{faqs.filter(f=>(f.q+' '+f.a).toLowerCase().includes(search.toLowerCase())).map(f=>{const i=faqs.indexOf(f);return <div key={f.q}><Button variant="ghost" onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i}>{f.q}<ChevronDown/></Button>{faq===i&&<p>{f.a}</p>}</div>})}{!faqs.some(f=>(f.q+' '+f.a).toLowerCase().includes(search.toLowerCase()))&&<p className="py-8 text-muted-foreground">Nenhuma resposta encontrada. Tente outro termo.</p>}</div></section><section className="support-contact"><span className="management-icon"><Mail/></span><div><h2>Precisa de uma ajuda a mais?</h2><p>Atendimento dedicado à sua conta OrdaX.</p></div><Button variant="outline" onClick={()=>setNotice(true)}>Falar com o suporte<ChevronRight/></Button></section></>}
 <Dialog open={notice} onOpenChange={setNotice}><DialogContent><DialogTitle>Atendimento não conectado</DialogTitle><DialogDescription>O canal oficial de suporte ainda não foi configurado. Nenhuma solicitação foi enviada.</DialogDescription><Button variant="outline" onClick={()=>setNotice(false)}>Entendi</Button></DialogContent></Dialog>
 </>
}
