import { Link } from '@tanstack/react-router';
import { ArrowUpRight, ArrowRight, Crown, ChartNoAxesCombined, CreditCard, ShieldCheck, UserRound, Pencil, CalendarDays, CircleDashed, Cpu, HardDrive, Zap, ChevronRight, LockKeyhole, Info, Sparkles, Fingerprint } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { sections } from '@/lib/account/model';
import { useOfficialAccountSession } from '@/lib/account/official-session';
import landscape from '@/assets/ordax-landscape.jpg';
import mark from '@/assets/ordax-mark.png';
export function ConsumptionChart({ period='Este mês' }: { period?: string }) {
 return <div className="usage-chart"><div className="chart-y"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div className="chart-field"><div className="chart-grid"/><div className="chart-empty"><ChartNoAxesCombined/><span>Seu consumo aparecerá aqui</span><small>Dados indisponíveis · {period.toLowerCase()}</small></div><div className="chart-x"><span>01</span><span>05</span><span>10</span><span>15</span><span>20</span><span>25</span><span>30</span></div></div></div>
}
export function Overview() {
 const official = useOfficialAccountSession();
 return <><section className="overview-hero"><img className="hero-landscape" src={landscape} width="1920" height="640" alt="Paisagem OrdaX com montanhas e um planeta luminoso"/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow"><span/> SEU UNIVERSO, CONECTADO</div><h1>Minha Conta<span>.</span></h1><p>Sua identidade, assinatura e recursos.<br className="mobile-break"/> Tudo em um só lugar.</p></div><span className="hero-caption">UMA CONTA. TODOS OS SEUS MUNDOS.</span></section>
 <section className="profile-banner"><div className="profile-identity"><div className="profile-avatar"><UserRound/><span><CircleDashed/></span></div><div><div className="flex items-center gap-2"><h2>Sua conta OrdaX</h2><span className="profile-label">Pessoal</span></div><p>Uma identidade para todo o seu universo.</p><Button variant="outline" size="sm" asChild><Link to="/dados-pessoais"><Pencil/>Ver perfil<ChevronRight/></Link></Button></div></div><div className="profile-facts"><div><span className="fact-icon"><CalendarDays/></span><div><small>Membro desde</small><strong>Não disponível</strong></div></div><div><span className="fact-icon violet"><Crown/></span><div><small>Plano atual</small><strong>Aguardando conexão</strong></div></div><div><span className="fact-icon mint"><ShieldCheck/></span><div><small>Status da conta</small><strong className="text-muted-foreground">{official.status==='authenticated'?'Conectada':official.status==='checking'?'Verificando':'Não conectada'}</strong></div></div></div></section>
 <div className="section-heading"><h2>Seu universo em resumo</h2><span>Visão geral da conta</span></div>
 <div className="summary-grid"><article className="account-card plan-card"><div className="card-title"><span className="icon-tile violet"><Crown/></span><span>Seu plano</span><span className="tiny-label">ASSINATURA</span></div><div className="plan-body"><div><h3>Mais possibilidades.<br/>Um só lugar.</h3><p>Seu plano e seus benefícios<br/>ficam disponíveis aqui.</p></div><img src={mark} width="126" height="126" alt="Símbolo OrdaX"/></div><Button className="plan-button" asChild><Link to="/assinatura">Ver assinatura<ArrowRight/></Link></Button></article>
 <article className="account-card resource-card"><div className="card-title"><span className="icon-tile cyan"><ChartNoAxesCombined/></span><span>Consumo de recursos</span><Link to="/consumo" aria-label="Ver consumo"><ArrowUpRight/></Link></div><p className="card-subtitle">Seus recursos, na medida do seu universo.</p><div className="resource-rows">{[{label:'Inteligência artificial',icon:Cpu,tone:'violet'},{label:'Armazenamento',icon:HardDrive,tone:'cyan'},{label:'APIs e serviços',icon:Zap,tone:'mint'}].map(r=><div className="resource-row" key={r.label}><r.icon className={r.tone}/><span>{r.label}</span><div className="resource-track"/><span className="resource-value">—</span></div>)}</div><span className="data-note"><CircleDashed/>Aguardando dados de consumo</span></article>
 <article className="account-card billing-card"><div className="card-title"><span className="icon-tile cyan"><CreditCard/></span><span>Faturamento</span><Link to="/faturamento" aria-label="Ver faturamento"><ArrowUpRight/></Link></div><div className="billing-content"><small>Próxima cobrança</small><h3>— <span>/ não disponível</span></h3><p>Nenhuma informação de cobrança conectada.</p></div><Link to="/faturamento" className="card-bottom-link"><CreditCard/>Pagamentos e faturas<ChevronRight/></Link></article></div>
 <div className="dashboard-grid"><section className="account-card chart-card"><div className="chart-heading"><div><h2><ChartNoAxesCombined className="cyan"/>Atividade de consumo</h2><p>Uma visão dos seus recursos ao longo do tempo.</p></div><span className="period-label"><CalendarDays/>Este mês</span></div><div className="chart-legend"><span><i className="legend-violet"/>Inteligência artificial</span><span><i className="legend-cyan"/>Armazenamento</span><span><i className="legend-mint"/>APIs e serviços</span></div><ConsumptionChart/><Link to="/consumo" className="chart-detail">Explorar consumo<ArrowRight/></Link></section>
 <section className="account-card security-summary"><div className="card-title"><span className="icon-tile mint"><ShieldCheck/></span><span>Sua segurança</span><Link to="/seguranca" aria-label="Ver segurança"><ArrowUpRight/></Link></div><div className="security-emblem"><ShieldCheck/></div><h3>Seu acesso. Seu controle.</h3><p>Mantenha sua identidade protegida<br/>em todos os seus dispositivos.</p><div className="security-row"><LockKeyhole/><span>Verificação em duas etapas</span><span>—</span></div><div className="security-row"><Fingerprint/><span>Sessões e dispositivos</span><span>—</span></div><Button variant="outline" asChild><Link to="/seguranca">Gerenciar segurança<ArrowRight/></Link></Button></section></div>
 <div className="section-heading management-heading"><h2>Gerencie sua conta</h2><span>Todo o controle, em um lugar.</span></div><section className="management-grid">{sections.filter(s=>!['/','/assinatura','/suporte'].includes(s.path)).map(s=><Link to={s.path} key={s.path} className="management-card"><span className="management-icon"><s.icon/></span><div><h3>{s.title}</h3><p>{s.description}</p></div><ChevronRight/></Link>)}</section>
 <section className="connection-notice"><Info/><div><strong>Seu próximo passo é conectar sua conta.</strong><p>Perfil, assinatura e consumo serão exibidos quando os serviços OrdaX estiverem integrados.</p></div><span><Sparkles/>O seu universo está pronto</span></section>
 </>
}
