title OrdaX Portable v2
linux /ordax/vmlinuz
initrd /ordax/initrd.gz
options quiet console=ttyS0,115200n8 console=tty0 rdinit=/sbin/ordax-portable-init loglevel=3 logo.nologo vt.global_cursor_default=0
