title OrdaX Portable v2 Recovery
linux /ordax/vmlinuz
initrd /ordax/initrd.gz
options console=ttyS0,115200n8 console=tty0 rdinit=/sbin/ordax-portable-init loglevel=7 ignore_loglevel logo.nologo ordax.mode=recovery
