// Code generated by tools/app-policy/render_runtime_package_source_policy.py; DO NOT EDIT.
// Source of truth: docs/contracts/runtime-component-package.json

package main

var canonicalExternalComponentSourceRepositories = map[string]string{
	"calculator": appsSourceRepository,
	"calendar": appsSourceRepository,
	"character-map": appsSourceRepository,
	"clock": appsSourceRepository,
	"colors": appsSourceRepository,
	"converter": appsSourceRepository,
	"image-viewer": appsSourceRepository,
	"media-player": appsSourceRepository,
	"notes": appsSourceRepository,
	"paint": appsSourceRepository,
	"pdf-viewer": appsSourceRepository,
	"studio": appsSourceRepository,
	"text-viewer": appsSourceRepository,
	"toolbox": appsSourceRepository,
}
