#!/usr/bin/env python3
"""Disposable end-to-end proof for component-bearing Profile activation.

This proof is intentionally CI-only. It uses the already staged and verified
Profile content slot plus an ephemeral trust key generated by the workflow.
It does not pin a production trust anchor and does not enable Stable/MVP.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

RUNTIME = Path(__file__).resolve().parents[2] / "system" / "surface" / "runtime"
sys.path.insert(0, str(RUNTIME))

from native_profile_activation_command import execute_profile_activation_command
from native_profile_component_inventory import read_profile_component_inventory
from native_profile_human_consent import ProfileHumanConsentAuthority
from native_profile_provisioning_executor import provision_verified_stage


def required_env(name: str) -> str:
    value = os.environ.get(name, "")
    if not value:
        raise RuntimeError(f"{name} is required")
    return value


def main() -> int:
    slot = required_env("PROFILE_SLOT")
    trust = required_env("PROFILE_TRUST")
    channel = required_env("PROFILE_CHANNEL")
    state_root = Path(required_env("PROFILE_STATE"))
    state_root.mkdir(parents=True, exist_ok=True)

    inventory_path = str(state_root / "inventory.json")
    receipt_root = str(state_root / "receipts")
    provisioning_lock = str(state_root / "provisioning.lock")
    activation_state = str(state_root / "activation-state.json")
    activation_lock = str(state_root / "activation.lock")

    provisioned = provision_verified_stage(
        slot,
        trust_path=trust,
        channel_bin=channel,
        inventory_path=inventory_path,
        receipt_root=receipt_root,
        lock_path=provisioning_lock,
        now_ms=2000,
    )
    inventory = read_profile_component_inventory(inventory_path)
    if len(inventory["entries"]) != 1:
        raise RuntimeError("Disposable Profile activation proof requires exactly one installed component")
    component = dict(inventory["entries"][0])

    import native_profile_activation_command as command_module

    manifest = {
        "space_kind": "professional",
        "state": "draft",
        "intelligence": {"external_provider_required": False},
        "security": {
            "auto_grant_privileges": False,
            "allow_unsigned_apps": False,
            "generic_shell_implied": False,
            "cross_space_memory": False,
        },
        "components": [{
            "id": component["id"],
            "kind": component["kind"],
            "version": component["version"],
            "required": True,
            "availability": "available",
            "sha256": component["sha256"],
            "signature_required": True,
        }],
    }
    original_manifest = command_module._canonical_manifest
    command_module._canonical_manifest = lambda slug, version: manifest
    authority = ProfileHumanConsentAuthority(secret=b"ordax-ci-profile-consent-proof-key", ttl_ms=60000)

    def consent_resolver(**kwargs):
        return authority.issue(
            permission_diff_sha256=kwargs["permission_diff_sha256"],
            expected_revision=kwargs["expected_revision"],
            space_id=kwargs["space_id"],
            profile=kwargs["profile"],
            now_ms=2500,
        )

    try:
        base = {
            "schema": "ordax.profile-activation-command/1",
            "expectedRevision": 0,
            "spaceId": "space-ci-profile-proof",
            "spaceKind": "professional",
            "profile": {"slug": "developer", "version": 1},
            "components": [component],
        }
        preview = execute_profile_activation_command(
            {**base, "action": "preview-activate"},
            distribution_profile="owner-development",
            state_path=activation_state,
            inventory_path=inventory_path,
            receipt_root=receipt_root,
            lock_path=activation_lock,
        )
        if preview["permissionDiff"]["requiresExplicitReview"] is not True:
            raise RuntimeError("Component-bearing Profile proof did not require explicit review")

        try:
            execute_profile_activation_command(
                {
                    **base,
                    "action": "activate",
                    "activatedAt": 3000,
                    "acceptedPermissionDiffSha256": preview["permissionDiffSha256"],
                },
                distribution_profile="stable-mvp",
                state_path=activation_state,
                inventory_path=inventory_path,
                receipt_root=receipt_root,
                lock_path=activation_lock,
                human_consent_authority=authority,
                human_consent_resolver=consent_resolver,
            )
        except PermissionError as exc:
            if "unavailable in this distribution" not in str(exc):
                raise
        else:
            raise RuntimeError("Stable/MVP unexpectedly accepted Profile mutation")

        activated = execute_profile_activation_command(
            {
                **base,
                "action": "activate",
                "activatedAt": 3000,
                "acceptedPermissionDiffSha256": preview["permissionDiffSha256"],
            },
            distribution_profile="owner-development",
            state_path=activation_state,
            inventory_path=inventory_path,
            receipt_root=receipt_root,
            lock_path=activation_lock,
            human_consent_authority=authority,
            human_consent_resolver=consent_resolver,
        )
        current = activated["state"]["spaces"][0]["current"]
        if current["components"] != [component]:
            raise RuntimeError("Activated Profile component identity differs from verified inventory")

        deactivated = execute_profile_activation_command(
            {
                "schema": "ordax.profile-activation-command/1",
                "action": "deactivate",
                "expectedRevision": 1,
                "spaceId": "space-ci-profile-proof",
            },
            distribution_profile="owner-development",
            state_path=activation_state,
            inventory_path=inventory_path,
            receipt_root=receipt_root,
            lock_path=activation_lock,
        )
        if deactivated["state"]["spaces"][0]["current"] is not None:
            raise RuntimeError("Profile deactivation proof did not clear current composition")

        rolled_back = execute_profile_activation_command(
            {
                "schema": "ordax.profile-activation-command/1",
                "action": "rollback",
                "expectedRevision": 2,
                "spaceId": "space-ci-profile-proof",
            },
            distribution_profile="owner-development",
            state_path=activation_state,
            inventory_path=inventory_path,
            receipt_root=receipt_root,
            lock_path=activation_lock,
        )
        restored = rolled_back["state"]["spaces"][0]["current"]
        if restored is None or restored["components"] != [component]:
            raise RuntimeError("Profile rollback did not restore verified component composition")

        receipt = json.loads(Path(provisioned["receiptPath"]).read_text(encoding="utf-8"))
        if receipt["health"]["authority"] != "none":
            raise RuntimeError("Disposable Profile proof receipt gained authority")

        print("PROFILE_COMPONENT_E2E_PROVISIONING=PASS")
        print("PROFILE_COMPONENT_E2E_PERMISSION_DIFF=PASS")
        print("PROFILE_COMPONENT_E2E_NATIVE_CONSENT=PASS")
        print("PROFILE_COMPONENT_E2E_ACTIVATION=PASS")
        print("PROFILE_COMPONENT_E2E_DEACTIVATION=PASS")
        print("PROFILE_COMPONENT_E2E_ROLLBACK=PASS")
        print("PROFILE_COMPONENT_E2E_STABLE_MUTATION_ALLOWED=NO")
        print("PROFILE_COMPONENT_E2E_PRODUCTION_TRUST_PROMOTED=NO")
        return 0
    finally:
        command_module._canonical_manifest = original_manifest


if __name__ == "__main__":
    raise SystemExit(main())
